version: '3.7'
services:
  mongodb:
    image: mongo
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo:/data/db
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mongo:
